### ISSUE TITLE
Swipe up/down doesn't react on Edge 80 (Chromium), Win10 tablet

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar-ui-qscroller#46]
On Lenovo tablet with Win10, Edge 80.0.361.50 (Chromium) scroller doesn't recognise swipe gestures for changing the content. 
You can only a click on the line and the clicked value is selected with the animation.

I added a css for s dialog window where the scrollers are but it doesn't help
```css
{
  overflow: auto;
  overscroll-behavior: contain;
  height: 300px;
}
```
Google guide for [pull-to-refresh](https://developers.google.com/web/updates/2017/11/overscroll-behavior). It works for the whole page but doesn't help for accepting swipe gestures for qscroller.

I'll try to investigate it more later along with iOS issue.
